import * as stylex from "@stylexjs/stylex"

export const padColorStyles = stylex.create({
  off: {
    backgroundColor: "#1f2937",
    color: "#e5e7eb",
    borderColor: "rgba(255, 255, 255, 0.12)",
  },
  red: {
    backgroundColor: "rgba(239, 68, 68, 0.42)",
    color: "#fee2e2",
    borderColor: "rgba(248, 113, 113, 0.72)",
  },
  amber: {
    backgroundColor: "rgba(245, 158, 11, 0.42)",
    color: "#fffbeb",
    borderColor: "rgba(251, 191, 36, 0.72)",
  },
  yellow: {
    backgroundColor: "rgba(234, 179, 8, 0.44)",
    color: "#fefce8",
    borderColor: "rgba(250, 204, 21, 0.72)",
  },
  green: {
    backgroundColor: "rgba(16, 185, 129, 0.42)",
    color: "#d1fae5",
    borderColor: "rgba(52, 211, 153, 0.72)",
  },
  cyan: {
    backgroundColor: "rgba(6, 182, 212, 0.42)",
    color: "#cffafe",
    borderColor: "rgba(34, 211, 238, 0.72)",
  },
  blue: {
    backgroundColor: "rgba(59, 130, 246, 0.42)",
    color: "#dbeafe",
    borderColor: "rgba(96, 165, 250, 0.72)",
  },
  purple: {
    backgroundColor: "rgba(139, 92, 246, 0.42)",
    color: "#ede9fe",
    borderColor: "rgba(167, 139, 250, 0.72)",
  },
  white: {
    backgroundColor: "rgba(248, 250, 252, 0.88)",
    color: "#020617",
    borderColor: "rgba(255, 255, 255, 0.92)",
  },
})

export const styles = stylex.create({
  app: {
    width: "100%",
    maxWidth: "none",
    minWidth: "360px",
    margin: 0,
    padding: {
      default: "18px",
      "@media (max-width: 760px)": "8px",
    },
    paddingBottom: "48px",
    boxSizing: "border-box",
    overflowX: "hidden",
  },
  header: {
    position: "sticky",
    top: 0,
    zIndex: 20,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "16px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
    backgroundColor: "rgba(8, 10, 18, 0.92)",
    backdropFilter: "blur(12px)",
    padding: "18px 0 16px",
  },
  eyebrow: {
    margin: "0 0 4px",
    color: "#a78bfa",
    fontSize: "0.78rem",
    fontWeight: 900,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  title: {
    margin: 0,
    fontSize: "clamp(1.9rem, 4vw, 3rem)",
    lineHeight: 1.02,
  },
  subtitle: {
    margin: "8px 0 0",
    color: "#93c5fd",
    fontSize: "0.9rem",
  },
  status: {
    flexShrink: 0,
    borderRadius: "999px",
    borderWidth: "1px",
    borderStyle: "solid",
    padding: "10px 14px",
    fontSize: "0.84rem",
    fontWeight: 900,
  },
  statusOnline: {
    borderColor: "rgba(16, 185, 129, 0.32)",
    backgroundColor: "rgba(16, 185, 129, 0.14)",
    color: "#a7f3d0",
  },
  statusOffline: {
    borderColor: "rgba(239, 68, 68, 0.34)",
    backgroundColor: "rgba(239, 68, 68, 0.12)",
    color: "#fecaca",
  },
  heroGrid: {
    display: "grid",
    gridTemplateColumns: {
      default: "1fr",
      "@media (min-width: 900px)": "360px 1fr",
    },
    gap: "16px",
  },
  panel: {
    marginTop: "16px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: "22px",
    backgroundColor: "rgba(18, 22, 38, 0.86)",
    boxShadow: "0 16px 48px rgba(0, 0, 0, 0.28)",
    padding: "16px",
  },
  qrPanel: {
    display: "grid",
    justifyItems: "center",
  },
  sectionHeader: {
    display: "grid",
    gap: "4px",
    marginBottom: "14px",
    width: "100%",
  },
  sectionTitle: {
    margin: 0,
    fontSize: "1rem",
  },
  sectionDescription: {
    margin: 0,
    color: "#94a3b8",
    fontSize: "0.9rem",
    lineHeight: 1.5,
  },
  qrWrap: {
    width: "min(100%, 320px)",
    borderRadius: "22px",
    backgroundColor: "#ffffff",
    padding: "12px",
  },
  qrImage: {
    display: "block",
    width: "100%",
    height: "auto",
  },
  qrPlaceholder: {
    display: "grid",
    placeItems: "center",
    width: "min(100%, 320px)",
    aspectRatio: "1 / 1",
    borderRadius: "22px",
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    color: "#94a3b8",
    fontWeight: 800,
  },
  urlBox: {
    width: "100%",
    marginTop: "14px",
    borderRadius: "14px",
    backgroundColor: "rgba(8, 10, 18, 0.74)",
    padding: "12px",
    color: "#ddd6fe",
    fontFamily: '"SFMono-Regular", Consolas, "Liberation Mono", monospace',
    fontSize: "0.86rem",
    overflowWrap: "anywhere",
    textAlign: "center",
  },
  errorText: {
    width: "100%",
    color: "#fecaca",
    fontSize: "0.85rem",
    overflowWrap: "anywhere",
  },
  networkList: {
    display: "grid",
    gap: "6px",
    width: "100%",
    marginTop: "10px",
    borderRadius: "14px",
    backgroundColor: "rgba(8, 10, 18, 0.42)",
    padding: "10px",
    color: "#94a3b8",
    fontSize: "0.76rem",
    lineHeight: 1.4,
    overflowWrap: "anywhere",
  },
  setupFlow: {
    display: "grid",
    gap: "10px",
    marginTop: "14px",
  },
  currentStep: {
    display: "grid",
    gridTemplateColumns: {
      default: "1fr",
      "@media (min-width: 720px)": "1fr auto",
    },
    alignItems: "center",
    gap: "14px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: "18px",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    padding: "14px",
  },
  currentStepWarning: {
    borderColor: "rgba(245, 158, 11, 0.34)",
    backgroundColor: "rgba(245, 158, 11, 0.09)",
  },
  currentStepReady: {
    borderColor: "rgba(16, 185, 129, 0.34)",
    backgroundColor: "rgba(16, 185, 129, 0.1)",
  },
  setupStepCopy: {
    display: "grid",
    gap: "6px",
    color: "#cbd5e1",
    lineHeight: 1.45,
  },
  setupActions: {
    display: "flex",
    gap: "10px",
    flexWrap: "wrap",
    justifyContent: "flex-end",
  },
  setupButton: {
    borderWidth: 0,
    borderRadius: "14px",
    backgroundColor: "#8b5cf6",
    color: "#ffffff",
    cursor: "pointer",
    fontWeight: 800,
    padding: "12px 14px",
  },
  setupButtonSecondary: {
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(167, 139, 250, 0.5)",
    backgroundColor: "rgba(255, 255, 255, 0.04)",
  },
  setupUnavailable: {
    color: "#fecaca",
    fontSize: "0.86rem",
  },
  portList: {
    display: "grid",
    gap: "6px",
    marginTop: "14px",
    borderRadius: "14px",
    backgroundColor: "rgba(8, 10, 18, 0.48)",
    padding: "12px",
    color: "#cbd5e1",
    fontSize: "0.86rem",
  },
  setupMessage: {
    margin: "14px 0 0",
    color: "#ddd6fe",
    fontSize: "0.88rem",
  },
  controlsLockedPanel: {
    minHeight: "180px",
  },
  apcPanel: {
    width: "100%",
    minWidth: 0,
    marginTop: "16px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.12)",
    borderRadius: "26px",
    backgroundColor: "#111827",
    boxShadow: "0 20px 60px rgba(0, 0, 0, 0.34)",
    padding: {
      default: "clamp(10px, 1.2vw, 18px)",
      "@media (max-width: 760px)": "8px",
    },
    boxSizing: "border-box",
    overflow: "hidden",
  },
  apcHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: "16px",
    alignItems: "flex-start",
    marginBottom: "16px",
  },
  apcTitle: {
    margin: "0 0 6px",
    fontSize: "1.15rem",
  },
  feedbackBadge: {
    flexShrink: 0,
    borderRadius: "999px",
    backgroundColor: "rgba(16, 185, 129, 0.12)",
    color: "#a7f3d0",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(16, 185, 129, 0.28)",
    padding: "8px 10px",
    fontSize: "0.78rem",
    fontWeight: 800,
  },
  feedbackBadgeWarning: {
    backgroundColor: "rgba(245, 158, 11, 0.12)",
    color: "#fde68a",
    borderColor: "rgba(245, 158, 11, 0.34)",
  },
  apcSurface: {
    width: "100%",
    minWidth: 0,
    display: "grid",
    gridTemplateColumns: {
      default: "minmax(0, 1fr)",
      "@media (min-width: 900px)": "minmax(352px, 1fr) clamp(72px, 6.4vw, 112px)",
    },
    gap: {
      default: "clamp(6px, 0.9vw, 14px)",
      "@media (max-width: 760px)": "6px",
    },
    borderRadius: "22px",
    backgroundColor: "#050814",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.08)",
    overflowX: "auto",
    overscrollBehaviorX: "contain",
    padding: {
      default: "clamp(8px, 1vw, 14px)",
      "@media (max-width: 760px)": "6px",
    },
    boxSizing: "border-box",
  },
  padMatrix: {
    minWidth: 0,
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(8, minmax(44px, 1fr))",
      "@media (max-width: 760px)": "repeat(8, minmax(36px, 1fr))",
    },
    gap: {
      default: "clamp(4px, 0.6vw, 8px)",
      "@media (max-width: 760px)": "4px",
    },
  },
  padButton: {
    position: "relative",
    overflow: "hidden",
    aspectRatio: "1 / 1",
    minWidth: "36px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.12)",
    borderRadius: {
      default: "12px",
      "@media (max-width: 760px)": "8px",
    },
    backgroundColor: "#1f2937",
    color: "#f8fafc",
    cursor: "pointer",
    display: "grid",
    alignContent: "center",
    justifyItems: "center",
    gap: "3px",
    padding: "4px",
    textAlign: "center",
    touchAction: "manipulation",
    userSelect: "none",
  },
  padButtonLit: {
    boxShadow: "0 0 22px rgba(255, 255, 255, 0.18)",
  },
  padLedLayer: {
    position: "absolute",
    inset: 0,
    borderRadius: "inherit",
    pointerEvents: "none",
    zIndex: 0,
  },
  padLabel: {
    position: "relative",
    zIndex: 1,
    color: "#f8fafc",
    textShadow: "0 1px 3px rgba(0, 0, 0, 0.85)",
    fontSize: {
      default: "0.7rem",
      "@media (max-width: 760px)": "0.56rem",
    },
    fontWeight: 900,
    lineHeight: 1.05,
    overflow: "hidden",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
  },
  padMeta: {
    position: "relative",
    zIndex: 1,
    color: "rgba(255, 255, 255, 0.92)",
    textShadow: "0 1px 3px rgba(0, 0, 0, 0.85)",
    fontSize: {
      default: "0.62rem",
      "@media (max-width: 760px)": "0.5rem",
    },
  },
  sceneColumn: {
    minWidth: 0,
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(4, minmax(54px, 1fr))",
      "@media (min-width: 900px)": "1fr",
    },
    gap: {
      default: "clamp(4px, 0.6vw, 8px)",
      "@media (max-width: 760px)": "4px",
    },
  },
  sceneLaunchButton: {
    position: "relative",
    overflow: "hidden",
    minWidth: "54px",
    minHeight: {
      default: "54px",
      "@media (min-width: 900px)": "44px",
    },
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(14, 165, 233, 0.42)",
    borderRadius: "12px",
    backgroundColor: "rgba(14, 165, 233, 0.14)",
    color: "#f8fafc",
    cursor: "pointer",
    display: "grid",
    placeItems: "center",
    gap: "2px",
    fontWeight: 900,
    padding: "8px",
  },
  sceneLabel: {
    position: "relative",
    zIndex: 1,
    color: "#f8fafc",
    textShadow: "0 1px 3px rgba(0, 0, 0, 0.85)",
  },
  sceneMeta: {
    position: "relative",
    zIndex: 1,
    color: "rgba(255, 255, 255, 0.92)",
    textShadow: "0 1px 3px rgba(0, 0, 0, 0.85)",
  },
  faderBank: {
    gridColumn: "1 / -1",
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(9, minmax(44px, 1fr))",
      "@media (max-width: 760px)": "repeat(9, minmax(36px, 1fr))",
    },
    gap: {
      default: "10px",
      "@media (max-width: 760px)": "4px",
    },
    width: "100%",
    minWidth: 0,
    overflowX: "visible",
    overscrollBehaviorX: "contain",
    marginTop: "10px",
  },
  faderStrip: {
    display: "grid",
    gridTemplateRows: {
      default: "166px auto auto auto",
      "@media (max-width: 760px)": "132px auto auto auto",
    },
    justifyItems: "center",
    alignItems: "center",
    gap: {
      default: "7px",
      "@media (max-width: 760px)": "5px",
    },
    minWidth: 0,
    overflow: "hidden",
    borderRadius: {
      default: "14px",
      "@media (max-width: 760px)": "10px",
    },
    backgroundColor: "rgba(255, 255, 255, 0.04)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.08)",
    padding: {
      default: "12px 4px 10px",
      "@media (max-width: 760px)": "9px 1px 8px",
    },
    cursor: "context-menu",
    touchAction: "none",
  },
  faderSliderArea: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    minWidth: 0,
    height: "100%",
    paddingTop: {
      default: "10px",
      "@media (max-width: 760px)": "8px",
    },
    paddingBottom: {
      default: "10px",
      "@media (max-width: 760px)": "8px",
    },
    touchAction: "none",
  },
  verticalSliderTrack: {
    position: "relative",
    width: {
      default: "42px",
      "@media (max-width: 760px)": "32px",
    },
    height: {
      default: "128px",
      "@media (max-width: 760px)": "98px",
    },
    borderRadius: "999px",
    backgroundColor: "transparent",
    touchAction: "none",
    overflow: "visible",
    outline: "none",
  },
  verticalSliderRail: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: "50%",
    width: "8px",
    transform: "translateX(-50%)",
    borderRadius: "999px",
    backgroundColor: "rgba(148, 163, 184, 0.22)",
    pointerEvents: "none",
  },
  verticalSliderFill: {
    position: "absolute",
    bottom: 0,
    left: "50%",
    width: "8px",
    transform: "translateX(-50%)",
    borderRadius: "999px",
    backgroundColor: "#8b5cf6",
    pointerEvents: "none",
  },
  verticalSliderThumb: {
    position: "absolute",
    left: "50%",
    zIndex: 2,
    transform: "translate(-50%, 50%)",
    width: {
      default: "28px",
      "@media (max-width: 760px)": "24px",
    },
    height: {
      default: "18px",
      "@media (max-width: 760px)": "16px",
    },
    borderRadius: "7px",
    backgroundColor: "#e5e7eb",
    borderWidth: "2px",
    borderStyle: "solid",
    borderColor: "#111827",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.35)",
    touchAction: "none",
  },
  faderValue: {
    color: "#ddd6fe",
    fontSize: {
      default: "0.72rem",
      "@media (max-width: 760px)": "0.58rem",
    },
    fontWeight: 900,
    lineHeight: 1,
  },
  faderName: {
    color: "#e5e7eb",
    fontSize: {
      default: "0.72rem",
      "@media (max-width: 760px)": "0.5rem",
    },
    textAlign: "center",
    lineHeight: 1.05,
    maxWidth: "100%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  faderCc: {
    color: "#94a3b8",
    fontSize: {
      default: "0.62rem",
      "@media (max-width: 760px)": "0.48rem",
    },
    lineHeight: 1,
  },
  warningText: {
    margin: "12px 0 0",
    borderRadius: "14px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(245, 158, 11, 0.38)",
    backgroundColor: "rgba(245, 158, 11, 0.1)",
    color: "#fde68a",
    padding: "10px 12px",
    fontSize: "0.86rem",
    lineHeight: 1.45,
  },
  lastCommandBar: {
    display: "grid",
    gap: "4px",
    marginTop: "12px",
    borderRadius: "14px",
    backgroundColor: "rgba(8, 10, 18, 0.7)",
    padding: "10px 12px",
    color: "#cbd5e1",
    fontSize: "0.82rem",
    overflowWrap: "anywhere",
  },
  fieldGroup: {
    display: "grid",
    gap: "6px",
    color: "#cbd5e1",
    fontSize: "0.84rem",
    fontWeight: 800,
  },
  checkboxField: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.14)",
    borderRadius: "12px",
    backgroundColor: "rgba(255, 255, 255, 0.04)",
    color: "#cbd5e1",
    padding: "10px 11px",
    fontSize: "0.84rem",
    fontWeight: 800,
  },
  textInput: {
    width: "100%",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.14)",
    borderRadius: "12px",
    backgroundColor: "#050814",
    color: "#f8fafc",
    padding: "10px 11px",
    outline: "none",
  },
  nativeSelect: {
    width: "100%",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.14)",
    borderRadius: "12px",
    backgroundColor: "#050814",
    color: "#f8fafc",
    padding: "10px 11px",
    outline: "none",
  },
  colorSelectRow: {
    display: "grid",
    gridTemplateColumns: "32px 1fr",
    gap: "8px",
    alignItems: "center",
  },
  colorPreview: {
    width: "32px",
    height: "32px",
    borderRadius: "10px",
    borderWidth: "1px",
    borderStyle: "solid",
  },
  modalBackdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 100,
    display: "grid",
    placeItems: "center",
    backgroundColor: "rgba(2, 6, 23, 0.74)",
    padding: "20px",
  },
  modalPanel: {
    width: "min(100%, 720px)",
    maxHeight: "min(92vh, 760px)",
    overflow: "auto",
    borderRadius: "24px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.14)",
    backgroundColor: "#111827",
    boxShadow: "0 30px 80px rgba(0, 0, 0, 0.5)",
    padding: "18px",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "14px",
    marginBottom: "16px",
  },
  modalTitle: {
    margin: 0,
    fontSize: "1.25rem",
  },
  iconButton: {
    width: "36px",
    height: "36px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.14)",
    borderRadius: "12px",
    backgroundColor: "rgba(255, 255, 255, 0.06)",
    color: "#f8fafc",
    cursor: "pointer",
    fontSize: "1.3rem",
    lineHeight: 1,
  },
  modalGrid: {
    display: "grid",
    gridTemplateColumns: {
      default: "1fr",
      "@media (min-width: 720px)": "repeat(2, minmax(0, 1fr))",
    },
    gap: "12px",
  },
  modalActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "10px",
    marginTop: "18px",
  },
  helpBox: {
    gridColumn: "1 / -1",
    display: "grid",
    gap: "6px",
    borderRadius: "14px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(14, 165, 233, 0.28)",
    backgroundColor: "rgba(14, 165, 233, 0.08)",
    color: "#bae6fd",
    padding: "12px",
    fontSize: "0.86rem",
    lineHeight: 1.45,
  },
})
